### ISSUE TITLE
1. Create a boilerplate express server (backend)

### ISSUE THREAD

**Issue by MadhavBahl** [TheLeanProgrammer/graphql-bootcamp#2]
Here's a simple one `up-for-grabs` / `good-first-issue`

Requirement: Create a simple backend server with `/` route returning a `Hello world` as a start of this project.

Make sure to put the server inside `server` directory

Intended directory structure

- client
- server
- README.md

**Comment by rdsol** [comment]
Hello Madhav, I didn't found any code here to contribute too. So, just sharing the code here itself. Find below boilerplate code for Express Server "Hello World!" :) Let's ride it from here to next level. Thanks!

```
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

**Comment by MadhavBahl** [comment]
Perfect @rdsol !

I'm trying build a simple full stack app to portray the use of GraphQL+Apollo

Please feel free to share if you have any ideas how things can be improved , or anything else in future. Definitely love feedbacks!

For this specific issue, I majorly opened for new-comers in open source so that they can get a taste of open source contributions

A quick boilerplate can be created using `npx express-generator`

**Comment by MadhavBahl** [comment]
Closing this issue - it'd be better if I add the initial files and set up a proper directory structure (to prevent confusion)
